# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pet < Formula
  desc "Simple command-line snippet manager"
  homepage "https://github.com/khulnasoft-lab/pet"
  version "0.3.0"

  depends_on "fzf"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/khulnasoft-lab/pet/releases/download/v0.3.0/pet_0.3.0_darwin_arm64.tar.gz"
      sha256 "40d5d829d4cce38596457f7ef71b745b91ac983750b1743b70d29b111724e9c8"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft-lab/pet/releases/download/v0.3.0/pet_0.3.0_darwin_amd64.tar.gz"
      sha256 "7ba9dd1e4bf363ab8148d33392c896eec867fc80674fec3703b20ad8507d2900"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/khulnasoft-lab/pet/releases/download/v0.3.0/pet_0.3.0_linux_armv6.tar.gz"
      sha256 "a0ec2a12206bcc8649f16ded77357ab6dc5f167d899affb4515441084b0402c1"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/khulnasoft-lab/pet/releases/download/v0.3.0/pet_0.3.0_linux_arm64.tar.gz"
      sha256 "a6bf468b96ead551956bcdb2a13fa021fe4e8eccfb694be7a213f386c9889572"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/khulnasoft-lab/pet/releases/download/v0.3.0/pet_0.3.0_linux_amd64.tar.gz"
      sha256 "3465a59bf98ba3dd1fc21c1d54583a2dd121724971bb0e8c70eba950feee7d3b"

      def install
        bin.install Dir['pet']
        zsh_completion.install "misc/completions/zsh/_pet"
      end
    end
  end

  test do
    system "#{bin}/pet"
  end
end
